//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class OctreeData
{
	public delegate bool SplitPolicy(Vector3 coord,float length, byte[] trace);
	public SplitPolicy splitPolicy;
	public delegate float ValueFunction(Vector3 coord);
	public ValueFunction valueFunction;
	public delegate Vector3 GradientFunction(Vector3 coord);
	public GradientFunction gradientFunction;
	public int numThreads = 0;
	public int threadLimit = 4;
	public readonly object _object = new object();

	public OctreeData ()
	{

	}

	public float[] CalculateValues(Vector3[] positions)
	{
		List<float> results = new List<float>();
		for (int i = 0; i < positions.Length; i++) {
			results.Add(valueFunction(positions[i]));
		}
		return results.ToArray();
	}
	public float CalculateValue(Vector3 position){
		return valueFunction(position);
	}
}